language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - cp contrib/env-sample .env
script:
  - flake8
  - pytest pypro --cov=pypro
after_success:
  - codecov